import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Hero from '@/components/Hero';
import About from "@/components/About"; 
import Services from "@/components/Services"
import Feature from "@/components/Feature"
import Goals from "@/components/Goals"
import Pricing from "@/components/Pricing"
import Testimonials from "@/components/Testimonials";
import Footer from "@/components/Footer";
import  Subscribe from "@/components/Subscribe"

import Image from "next/image";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Navbar/>

      < Hero/>

      <About/>

      <Services/>

      <Feature/>

      <Goals/>

      <Pricing/>

      <Testimonials/>

       <Subscribe/>

       <Footer />




        {children}
       
      </body>
    </html>
  );
}
